create table author (
	author_id int generated by default as identity primary key,
	first_name varchar(50) not null,
	last_name varchar(50),
	birth_year int
);

create table books (
	book_id int generated by default as identity primary key,
	title varchar(100),
	author_id int,
	publication_year int,
	price decimal(6, 2)
);

create table categories (
	category_id int generated by default as identity primary key,
	category_name varchar(50) not null
);

create table book_categories (
	book_id int,
	category_id int,

	primary key (book_id, category_id),
	constraint fk_book_id foreign key (book_id) references books(book_id),
	constraint fk_category_id foreign key (category_id) references categories(category_id)
);


insert into author(first_name, last_name, birth_year)
values 
	('John', 'duo', 1775),
	('Casey', 'raw', 1903),
	('Adam', 'baroda', 1899),
	('Mark', 'mohanne', 1890),
	('Jane', 'smith', 1965);


insert into books(title, author_id, publication_year, price)
values
	('Pride and Prejudice', 1, 1813, 12.89),
	('1984', 2, 1949, 12.89),
	('Animal Farm', 2, 1945, 12.89),
	('The old man and the sea', 3, 1952, 12.89),
	('Death of the neal', 4, 1934, 12.89),
	('Emma', 4, 1937, 12.89),
	('For whom the Bell tolls', 1, 1815, 12.89),
	('Murder on the Orient Express', 3, 1940, 12.89);


insert into categories (category_name)
values
	('Fiction'),
	('Classic'),
	('Romance'),
	('Political'),
	('Mystery'),
	('Adventure');

insert into book_categories (book_id, category_id)
values
	(1, 1), (1, 2), (1, 3),
	(2, 1), (2, 2), (2, 4),
	(3, 1), (3, 2), (3, 4),
	(4, 1), (4, 2), (4, 6),
	(5, 1), (5, 5),
	(6, 1), (6, 5),
	(7, 1), (7, 2), (7, 3),
	(8, 1), (8, 2), (8, 6);


select * from author;
select * from books;
select * from book_categories;

-- Retrieve books with their author's information.
select a.first_name, a.last_name, a.birth_year, b.title, b.publication_year, b.price from author as a
inner join books as b
on a.author_id = b.author_id where b.publication_year > 1900 order by a.birth_year asc;


-- How many books each authors has written.
select a.first_name, a.last_name, count(*) as book_count from author as a
inner join books as b
on a.author_id = b.author_id group by a.author_id;






























